env:
  SERVICE_NAME: rover
  PIPELINE_VERSION: "1.0.${BUILDKITE_BUILD_NUMBER}"
  TAG: "1.0.${BUILDKITE_BUILD_NUMBER}"

steps:
  - label: "Build and Publish"
    key: build

    command: ./ops/ci/build.sh
    env:
      YARN_CACHE_FOLDER: "/yarn_home/.cache"
    plugins:
      - ailohq/git-tag#v1.0.13:
          release: false
          version: v$PIPELINE_VERSION
